### Register
POST http://localhost:2000/api/auth/register
Content-Type: application/json

{
  "username": "minhtam",
  "email":"minhtam@gmail.com",
  "password": "minhtam"
}

### Login
POST http://localhost:2000/api/auth/login
Content-Type: application/json

{
  "email": "tam@gmail.com",
  "password": "tam"
}

### Get habits
GET http://localhost:2000/api/habits/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTE2NDYwNDI3M2RlYzE1ODhhNjg0NTEiLCJpYXQiOjE2OTc1NDQ1MTF9.1Q2gDezCNGmDU9j35U3dUViNsyV6W85oG6CDPHEV6z0

### Create habit
POST http://localhost:2000/api/habits

Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTE2NDYwNDI3M2RlYzE1ODhhNjg0NTEiLCJpYXQiOjE2OTczNTI0Njl9.5wwNIYxnJECsA17UfSwwNQ-edc3H0kJ9enhP9rJ6Gp0

{
  "description": "code 4 hours a day",
  "type":"good"
}

### Update habit
PUT http://localhost:2000/api/habits/652b8b47167f2ba2c17d9cda
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTE2NDYwNDI3M2RlYzE1ODhhNjg0NTEiLCJpYXQiOjE2OTczNTE4MzB9.PaiDoOEBu_6EM9aEFzTGIc1J_hgsueh0tlYc5geVOkU

{
  "description": "code 4 hours a day at a coffee shop",
  "type":"good"
}

### Delete habit
DELETE http://localhost:2000/api/habits/652b8b47167f2ba2c17d9cda
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTE2NDYwNDI3M2RlYzE1ODhhNjg0NTEiLCJpYXQiOjE2OTczNTE4MzB9.PaiDoOEBu_6EM9aEFzTGIc1J_hgsueh0tlYc5geVOkU

### Track habit
PUT http://localhost:2000/api/habits/6527ff513bc4769f6b04b3b0/track
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTE2NDYwNDI3M2RlYzE1ODhhNjg0NTEiLCJpYXQiOjE2OTc3NzIxNDV9.PB-sjTqjmEFEa714w3vOka29wAdCOPi_DBTbYj5x0Us

{
  "completion_date": "2023-10-17T00:00:00.000Z",
  "complete": true
}

### Get instruction
GET http://localhost:2000/api/instructions/
Content-Type: application/json

{
  "stage": "analyse",
  "day": 7
}

### Get motivation
GET http://localhost:2000/api/motivations/
Content-Type: application/json

### Get result
GET http://localhost:2000/api/results/
Content-Type: application/json

{
  "result_date": "analyse",
  "day": 7
}