@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTE2NDYwNDI3M2RlYzE1ODhhNjg0NTEiLCJpYXQiOjE2OTk0OTg5MDN9.CwKnnQoPFOwTd2NCIM-I_m7NZHtHrssJvOJJ2YqEPQ4

### Register
POST http://localhost:2000/api/auth/register
Content-Type: application/json

{
  "username": "minhtam",
  "email":"minhtam@gmail.com",
  "password": "minhtam"
}

### Login
POST http://localhost:2000/api/auth/login
Content-Type: application/json

{
  "email": "tam@gmail.com",
  "password": "tam"
}

### Get all habits
GET http://localhost:2000/api/habits/me
Content-Type: application/json
Authorization: Bearer {{token}}

### Create habit
POST http://localhost:2000/api/habits
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "description": "sleep 7 hours a day",
  "type":"good"
}

### Update habit
PUT http://localhost:2000/api/habits/654b52f3d4440be1e0e592ac
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "description": "code 4 hours a day at a coffee shop",
  "type":"good"
}

### Delete habit
DELETE http://localhost:2000/api/habits/652b8b47167f2ba2c17d9cda
Authorization: Bearer {{token}}

### Track habit
PUT http://localhost:2000/api/habits/6527ff513bc4769f6b04b3b1/track
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "completion_date": "2023-11-07T00:00:00Z",
  "complete": false
}

### Get instruction
GET http://localhost:2000/api/instructions/
Content-Type: application/json

{
  "stage": "analyse",
  "day": 1
}

### Get motivation
GET http://localhost:2000/api/motivations/
Content-Type: application/json

### Get result
GET http://localhost:2000/api/results/
Content-Type: application/json

{
  "result_date": "analyse",
  "day": 7
}